### ISSUE TITLE
Mutation hangs if not imported

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#269]
If you define a mutation endpoint in the graphql schema that is not imported into the SQRL script and then try to invoke the mutation, GraphiQL just hangs.

**Comment by henneberger** [comment]
I'm having trouble replicating this. They are architecturally completely separated so I'm not sure how one could impact the other. Were you using docker-compose with only a single thread?

**Comment by henneberger** [comment]
Cannot replicate
