### ISSUE TITLE
Integer type in GraphQL

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#344]
We should internally represent all integers as 64 bit so we only have one integer type.
However, in GraphQL the default int scalar is a 32 bit value.

Suggestion:
we map integer to int in GraphQL by default but also provide a custom BigInt scalar that's compatible with Apollo GraphQL so users can explicitly set that in the api when they expect very large values (which will be pretty likely since epoch millis doesn't fit into 32 bits)

We add a server error when we try to return an integer that exceeds 32 bits as a int.
Later, we can try to automatically infer whether int or bigint is the better option.

**Comment by henneberger** [comment]
Closing in favor of #744
