### ISSUE TITLE
Don't use CREATE TABLE IF NOT EXIST

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#348]
and instead use normal CREATE TABLE statements so that the database fails early if the user accidentally forgets to destroy the volumes from a previous run.

Otherwise, they get a cryptic exception later about not being able to insert data.

**Comment by henneberger** [comment]
In lieu of stateful schema migration mechanism, the create-or-replace paradigm is important for init containers in production environments.
