### ISSUE TITLE
Write SQL queries and views

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#401]

**Comment by mbroecheler** [comment]
https://github.com/DataSQRL/sqrl/pull/402

**Comment by mbroecheler** [comment]
There are 4 different types of queries that get enumerated:

- Query on table (i.e. table function without arguments): this creates a view
- Permutated query on table: those are ignored (should just be queries against the view)
- Table functions with arguments: query with named parameters
- Relationships: query with named parameters (and file name indicating it's a relationship)

**Comment by mbroecheler** [comment]
- is it permutated (boolean)?
- is it a relationship (boolean)?
- does it have arguments (list of arguments)?

**Comment by mbroecheler** [comment]
API Query nameId needs to be the whole namepath plus an (optional) integer to disambiguate overloaded table functions

**Comment by mbroecheler** [comment]
@henneberger adds the following:
- Namepath and List<String> for the arguments to APIQuery
- Look into how to generate queries with named dynamic parameters (instead of indexed ones as we are currently generating)
- Generate only APIQueries for visible table functions in SQRL script (no access by primary key)

Matthias does:
- Figure out how the user can communicate that they only want SQL output
- Generate the queries

**Comment by henneberger** [comment]
This will be transformed into a separate issue. All database engines should generate views by default and then reference those views in graphql queries when we split the workload.
