### ISSUE TITLE
Generate docker compose with custom configuration

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#422]
When providing a custom configuration file (i.e. not the default generated one) in one of these ways:
`docker run --rm -v $PWD:/build datasqrl/cmd:dev compile rave.sqrl --mnt $PWD -c configuration_package.json`
or by renaming that file to  package.json

An error occurs when the resulting job is run in docker compose:
`no configuration file provided: not found`

**Comment by mbroecheler** [comment]
Actually, the issue is that DataSQLR does not write out a docker-compose file when providing a custom configuration.

**Comment by mbroecheler** [comment]
We should always generate the docker-compose file and submit-flink.sh

**Comment by mbroecheler** [comment]
And add a notice to the user if they provide a custom config that they may have to adjust the docker-compose manually.

**Comment by henneberger** [comment]
Doesnt appear to be valid anymore
