### ISSUE TITLE
Move to regular expression for file/topic discovery

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#434]
and make sure we use that regex in the table descriptor of the source.
Currently, we are using "prefix" for topic discovery in kafka but are not using it for constructing the topic name when we read the data which is a bug.

Rather than fix that bug in isolation, we want to move to a standard pattern for how we discover files and topics so it is consistent. It should be a regex with one capturing group, and the capturing group gets replaced by the identifier.

Also, for files we should not have a "beginning of string" identifier so that people can match this against variable paths.

**Comment by henneberger** [comment]
We no longer have schema discovery for kafka.
