### ISSUE TITLE
Running credit card example seems to loose half the data

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#482]
When using the attached data files for the credit card example (replacing the current files), only half the data seems to be processed.
[missing_data.zip](https://github.com/DataSQRL/sqrl/files/13982400/missing_data.zip)

**Comment by mbroecheler** [comment]
I suspect this is due to file splits since it's roughly half the data that shows up. But only the first half which is curious.

**Comment by henneberger** [comment]
Was a flink bug. Closing since we've moved to 1.19
