### ISSUE TITLE
Join Types are not translated correctly

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#500]
Only `JOIN` should be annotated with `DEFAULT`. All other join types should be fixed.
Specifically, `LEFT JOIN` should not be annotated with default but `inner` since there is no way to specify the type of left join.

In other words, we will only infer the join type when the user just writes `JOIN` (and therefore the join is ambiguous). In all other cases, the join is explicitly specified.

**Comment by henneberger** [comment]
I think this is fixed
