### ISSUE TITLE
Unable to create microservices in a directory different than ./build

### ISSUE THREAD

**Issue by gfusco-mdsol** [DataSQRL/sqrl#529]
I tried to pass the `--target` command to the `compile`, but I wasn't able to generate a deployment to a different directory.

I tried to pass a directory both as absolute path a relative one. For example I tried something like
```
docker run --rm -v $PWD:/build datasqrl/cmd compile --target="/tmp/build" my_script.sqrl
```
I also tried to create the absolute path directory before, but it was still empty after running the command (and I didnt' get any particular error in from the compilation itself, but it looks like all files went to the local `build` directory).

I tried a relative path, like
```
docker run --rm -v $PWD:/build datasqrl/cmd compile --target="./test" my_script.sqrl
```
and most files were in `./build`, and only some in `./test`

**Comment by henneberger** [comment]
This looks fixed
