### ISSUE TITLE
Run subsets of tests

### ISSUE THREAD

**Issue by henneberger** [DataSQRL/sqrl#657]
Instead of running all tests, we can pass a cli argument or package json entry to run only a subset of tests.

**Comment by Jardo-51** [comment]
Hi. Just out of curiosity, what does "subset of tests" mean? Can you provide a more detailed description of how the tests should be divided into subsets?

Perhaps by modules, or unit/integration tests, or something else?

**Comment by henneberger** [comment]
Closing unless there is interest. It doesn't appear that subsets of tests is well defined.
