### ISSUE TITLE
Subscriptions no longer working

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#666]
Trying to invoke a subscription in GraphiQL returns:
```
{
  "errors": [
    {
      "isTrusted": true
    }
  ]
}
```

Can be reproduced by running the iot example: https://github.com/DataSQRL/datasqrl-examples/tree/datasqrl0.5/iot-sensor-metrics

The expected behavior is running the subscription should wait, then it should be possible to run the following mutation in another graphiql window and see the results appear:
```
mutation {
AddReading(metric: {sensorid: 1, temperature: 101.5}) {
        sensorid
    }
}
```

**Comment by henneberger** [comment]
Reverted 2ed9ddfc0178c4f3bdc38973c69f4f4536db427b and pushed to v0.5

@nandorsoma seems the issue was in the refactoring of the graphql servlet name
