### ISSUE TITLE
Enable Exporting and Importing of Logs

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#721]
Make it possible to export to the log engine. This should be easy and should be done similarly to exporting to a logger.

The import part is tricky because the module loading happens before parsing the import statement.

This is how it should look like in sqrl:
```
EXPORT MyStateTable To log.MyStateTableAsStream:

IMPORT MyStateTableAsStream;
```

**Comment by henneberger** [comment]
Duplicate of #731
