### ISSUE TITLE
Do we need Kafka UI in the sqrl test command?

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#746]
It comes a lot of resources to run in docker.

**Comment by henneberger** [comment]
It uses 300mb out of the 3gb for the normal stack. Maybe we should reconsider using docker compose as the test runner since it generally is very hard to work with. We can migrate it to using the same code as the run command.

**Comment by henneberger** [comment]
Fixed when we moved to the new test runner.
