### ISSUE TITLE
Flink graph mismatch between sqrl and flink sql when SQL using IN clause with morethan 100 stream_uuids

### ISSUE THREAD

**Issue by stamminenimdsol** [DataSQRL/sqrl#760]
datasqrl:

<img width="1677" alt="image" src="https://github.com/user-attachments/assets/483358b4-1e7e-4024-a765-7c5ec6bc9b47">

flink sql:

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/4ff7caac-b143-477b-a550-56386689b268">

**Comment by henneberger** [comment]
I believe this was resolved in #762
