### ISSUE TITLE
Iceberg Connector Issues: Temporal Join and Heap Memory

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#770]
When using the Iceberg connector in the `sqrl run` command, there are two issues:

1) Temporal joins don't work. It looks like the idleness configuration isn't being respected.

2) It takes up a lot of heap space. In particular when doing an inner join. It looks like the rocksdb setting isn't being respected. But even without RocksDB, it's not clear why so much heap is allocated for such trivial amounts of data.

See: https://github.com/DataSQRL/datasqrl-examples/pull/19 for code and how to reproduce.

**Comment by henneberger** [comment]
The partition key hint resolves the memory issue. However, are temporal joins still an issue?

**Comment by Zesky665** [comment]
This one doesn't appear anymore in the finance-credit-card example.
 But I think that more testing is needed.
