### ISSUE TITLE
When a package doesn't have topic list, the UI crashes on the user's home screen

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#828]
I uploaded a package that doesn't contain the `topic` field in the `package` subsection of package.json and the UI crashes after that with the following error:
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

I think it is ok, to upload a package without topic. (previously this field was called as "keywords")

See my user for example: https://dev.datasqrl.com/nandorsoma

**Comment by henneberger** [comment]
@nandorsoma is this complete?

**Comment by nandorsoma** [comment]
@henneberger, yes. Idk why the linked PR didn't close this automatically.
