### ISSUE TITLE
Kafka sources and sinks

### ISSUE THREAD

**Issue by mbroecheler** [DataSQRL/sqrl#86]
Add support for Kafka sinks (ie. implement discoverSink) and Kafka TableDescriptor.

Add test cases for Kafka sources and sinks. Try to extend the existing tests and make sure they work.

**Comment by henneberger** [comment]
Kafka sink added in f2b7953757c039fba7e6476c2e0f0192dd575d70

More testing is necessary.

**Comment by henneberger** [comment]
fixed
