### ISSUE TITLE
UDF jar resolution when using the SQRL repository

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#863]
There is an issue where the *.functions.json metadata was generating incorrect relative paths for local UDFs. The solution involves relativizing the paths to the root directory, ensuring they can be correctly resolved later by buildPath after the local UDFs is copied to the build folder.

This issue only arises when sqrl compile is executed outside of the root directory.

**Comment by henneberger** [comment]
Resolved in #985. We can continue to use the *.function.json metadata.
