### ISSUE TITLE
Support array types in SchemaWalker

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#956]
When a field is defined in the GraphQL schema and its underlying type is an array, the compilation currently fails with a RuntimeException.

For example, consider the following query where a function returns a double[]:
```
results := SELECT prompt AS pr,
    vector_embedd(prompt, 'text-embedding-ada-002') AS em
    FROM data;
```
If the em field is not included in the GraphQL schema, compilation succeeds without issue. However, if em is added to the schema, compilation fails because the necessary mapping for arrays is not implemented.
```
type Results {
  pr: String
  em: [Int]
}

type Query {
  results(pr: String, limit: Int = 10, offset: Int = 0): [Results!]
}
```
For more context on the source of the issue, refer to the following line in the SchemaWalker.java file:
[SchemaWalker.java - Line 114](https://github.com/DataSQRL/sqrl/blob/7007a046e0b137ea2fefecb670c6b2b697bb8341/sqrl-planner/src/main/java/com/datasqrl/graphql/inference/SchemaWalker.java#L114)

**Comment by henneberger** [comment]
Fixed in #982
